name: Convert PlantUML to PNG

on:
  workflow_dispatch:
    inputs:
      plantuml_url:
        description: 'PlantUML URL to convert'
        required: true
        default: 'https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create output directory
        run: mkdir -p output
      
      - name: Direct PlantUML Conversion
        run: |
          # Extract code from URL
          URL="${{ github.event.inputs.plantuml_url }}"
          echo "Processing URL: $URL"
          
          # Extract the code from the URL
          URL_CODE=$(echo "$URL" | grep -oE 'uml/[^/]+' | cut -d'/' -f2 || echo "SyfFKj2rKt3CoKnELR1Io4ZDoSa70000")
          echo "Extracted code: $URL_CODE"
          
          # Direct download from PlantUML server
          echo "Downloading PNG directly from PlantUML server..."
          curl -s "https://www.plantuml.com/plantuml/png/$URL_CODE" --output "output/diagram.png"
          
          # Check if file was created successfully
          if [ -f "output/diagram.png" ]; then
            echo "✅ Diagram converted successfully to PNG"
            ls -la output/
          else
            echo "❌ Failed to convert diagram"
            exit 1
          fi
      
      - name: Upload PNG as artifact
        uses: actions/upload-artifact@v3
        with:
          name: plantuml-diagram
          path: output/*.png
          if-no-files-found: error
